import 'package:flutter/material.dart';

List<Map<String, dynamic>> chats = [
  {
    "icongBg": Colors.yellow,
    "icon": Icons.account_circle,
    "name": "Amol Tajane",
    "message": "ढवळे आहे ६२ ला कुडेकर नाही",
    "dateTime": "29/05/25",
    "chatType": "Incoming",
    "isPin": true,
    "responseCount": 0,
    "isSnozzed": false,
  },
  {
    "icongBg": Colors.green,
    "icon": Icons.face,
    "name": "Savi Nirgun",
    "message": "10:41 ls msg received",
    "dateTime": "11:07 am",
    "chatType": "Outgoing",
    "isPin": true,
    "responseCount": 0,
    "isSnozzed": false,
  },

  {
    "icongBg": Colors.blue,
    "icon": Icons.whatshot,
    "name": "Prashant Nirgun",
    "message": "If I have Poppings-Regular font and",
    "dateTime": "Yesturday",
    "chatType": "Outgoing",
    "isPin": true,
    "responseCount": 0,
    "isSnozzed": false,
  },
  {
    "icongBg": Colors.deepPurple,
    "icon": Icons.webhook,
    "name": "Crazy Cousins 🐈 🐱 🐴",
    "message": "Happy Birthday ",
    "dateTime": "2:30 pm",
    "chatType": "Outgoing",
    "isPin": false,
    "responseCount": 8,
    "isSnozzed": true,
  },
  {
    "icongBg": Colors.deepOrange,
    "icon": Icons.emoji_events,
    "name": "Santosh Bochare",
    "message": " Tera to beda gark ho gaya hai",
    "dateTime": "1:55 pm",
    "chatType": "Outgoing",
    "isPin": false,
    "responseCount": 0,
    "isSnozzed": false,
  },
  {
    "icongBg": Colors.greenAccent,
    "icon": Icons.coronavirus,
    "name": "Sathe Premises",
    "message": "Tomorrow I am going to your place",
    "dateTime": "1:55 pm",
    "chatType": "Outgoing",
    "isPin": false,
    "responseCount": 0,
    "isSnozzed": false,
  },
  {
    "icongBg": Colors.grey,
    "icon": Icons.handshake,
    "name": "Allot Digital Solutions",
    "message": "Good morning",
    "dateTime": "12:06 pm",
    "chatType": "Outgoing",
    "isPin": false,
    "responseCount": 0,
    "isSnozzed": false,
  },
  {
    "icongBg": Colors.red,
    "icon": Icons.format_shapes,
    "name": "Kailash Wayker",
    "message": "Photo",
    "dateTime": "12:06 pm",
    "chatType": "Incoming",
    "isPin": false,
    "responseCount": 0,
    "isSnozzed": false,
  },
];

List<Map<String, dynamic>> bottomTabs = [
  {"icon": Icons.chat, "text": "Chat"},
  {"icon": Icons.restart_alt, "text": "Update"},
  {"icon": Icons.groups, "text": "Communities"},
  {"icon": Icons.call, "text": "Calls"},
];

List<Map<String, dynamic>> topLists = [
  {"isSelected": true, "text": "All"},
  {"isSelected": false, "text": "Unread 1"},
  {"isSelected": false, "text": "Favourities"},
  {"isSelected": false, "text": "Groups"},
  {"isSelected": false, "text": "Family"},
  {"isSelected": false, "text": "Office"},
];

List<Map<String, dynamic>> stauts = [
  {
    "icongBg": Colors.teal,
    "icon": Icons.paid,
    "name": "Santosh Bochare",
    "dateTime": "1:55 pm",
  },
  {
    "icongBg": Colors.purpleAccent,
    "icon": Icons.watch_later,
    "name": "Vaibhav Apte Awfis",
    "dateTime": "12:06 pm",
  },
  {
    "icongBg": Colors.white,
    "icon": Icons.account_circle,
    "name": "Vijay Bhai",
    "dateTime": "1:16 am",
  },
  {
    "icongBg": Colors.blue,
    "icon": Icons.pending,
    "name": "Prashant Nirgun",
    "dateTime": "10:43 am",
  },
  {
    "icongBg": Colors.deepPurple,
    "icon": Icons.stars,
    "name": "Crazy Cousins 🐈 🐱 🐴",
    "dateTime": "2:30 pm",
  },
  {
    "icongBg": Colors.greenAccent,
    "icon": Icons.group_work,
    "name": "Sathe Premises",
    "dateTime": "1:55 pm",
  },
  {
    "icongBg": Colors.grey,
    "icon": Icons.group_work,
    "name": "Allot Digital Solutions",
    "dateTime": "12:06 pm",
  },
  {
    "icongBg": Colors.white,
    "icon": Icons.face,
    "name": "Savi Nirgun",
    "dateTime": "11:07 am",
  },
];
